module.exports = {
    empty_message: "Thuoc tinh %s khong duoc de trong",
    size_string_message: "thuoc tinh %s dai toi nhieu %d va toi da %d ki tu",
    number_message: "thuoc tinh %s phai la so",
    url_message: "thuoc tinh %s phai la URL",
    connect_mongdb: "Connect mongoDB successfully",
    error_mongdb: "Could not connect to mongodb",
    error: "Error",
    product_is_not_valid: "Product is not valid",
    user_is_not_valid: "User is not valid",
    user_is_not_exist: "User is not exist",
    delete_product_successfully: 'Delete product successfully',
    product_create_failed: 'Product create failed',
    product_is_existed: 'Product is existed',
    email_is_existed: 'Email is existed',
    register_failed: 'Register failed',
    user_is_not_existed: 'User is not existed',
    message_not_authenticate: 'You are not authenticate',
    not_found_token: 'Not found token',
    not_permission: 'You are not permission',
    not_found_secret_key: 'Not found secret key',
    token_expired: 'Token expired',
}